stages:
  - install
  - lint
  - deploy

cache:
  untracked: true
  paths:
    - node_modules/

# beta就是alibeta，分支的流程开始###
job-install-beta:
  stage: install
  script:
    - whoami
    - id
    - echo $SHELL
    - pwd
    - source ~/.bashrc
    - nvm use 8
    - node -v
    - yarn --registry=https://registry.npm.taobao.org
  only:
    - alibeta
  tags:
    - nodeci-beta

job-lint-beta:
  stage: lint
  script:
    - whoami
    - id
    - pwd
    - source ~/.bashrc
    - nvm use 8
    - node -v
    - npm run lint
  only:
    - alibeta
  tags:
    - nodeci-beta

job-deploy-beta:
  stage: deploy
  script:
    - id
    - pwd
    - cp -rf /home/builds/4eb36916/0/Frontend/act-jyds/* /root/frontend/beta/node-act-jyds/application/
  only:
    - alibeta
  tags:
    - nodeci-beta

# beta就是alibeta，分支的流程开始###

# production分支的流程开始###
job-install-prod:
  stage: install
  script:
    - whoami
    - id
    - echo $SHELL
    - pwd
    - source ~/.bashrc
    - nvm use 8
    - node -v
    - yarn
  only:
    - production
  tags:
    - nodeci-prod

job-lint-prod:
  stage: lint
  script:
    - whoami
    - id
    - pwd
    - source ~/.bashrc
    - nvm use 8
    - node -v
    - npm run lint
  only:
    - production
  tags:
    - nodeci-prod

job-deploy-prod:
  stage: deploy
  script:
    - id
    - pwd
    - cp -rf /home/builds/12957248/0/Frontend/act-jyds/* /root/frontend/prod/node-act-jyds/application/
  only:
    - production
  tags:
    - nodeci-prod
# production分支的流程开始###
